name: Build keymap

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@1.5.1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: |
            # Corne Keymap - ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
          artifacts: |
            build/artifacts/*.zip
            keymap-drawer/*.svg
