name: Render keymap

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "keymap-drawer/config.yml"

jobs:
  render:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap-drawer/config.yml"
      draw_args: "corne: '--ghost-keys 13 14 15 16 19 20 21 22'"
      output_folder: "keymap-drawer"
